def html_page() -> str:
    return """<!doctype html>
<html lang='vi'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>
<title>VinAI Admissions MAS</title>
<style>body{font-family:system-ui,sans-serif;max-width:1180px;margin:0 auto;padding:24px;background:#f4f6f8;color:#17202a}h1{margin:0 0 4px}p{color:#5b6570}.grid{display:grid;grid-template-columns:minmax(300px,1fr) minmax(300px,1fr);gap:16px}section{background:#fff;border:1px solid #d9e0e6;border-radius:8px;padding:16px;margin:16px 0}label{display:block;font-weight:600;margin:10px 0 5px}textarea,input{width:100%;box-sizing:border-box;border:1px solid #c8d0d8;border-radius:5px;padding:10px;font:inherit}textarea{min-height:130px}button{margin-top:12px;background:#1261a0;color:#fff;border:0;border-radius:5px;padding:10px 16px;cursor:pointer}button:disabled{opacity:.6}.metric{display:inline-block;margin:4px 8px 4px 0;padding:5px 8px;background:#eef3f7;border-radius:4px;font-size:.9em}.ok{color:#087443}.warn{color:#a15c00}.source,.evidence,.event{border-top:1px solid #e5e9ed;padding:9px 0}.muted{color:#687581;font-size:.88em}pre{white-space:pre-wrap;overflow:auto;background:#101820;color:#dce9f2;padding:12px;border-radius:5px;max-height:380px}.stack{max-height:320px;overflow:auto}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style></head><body>
<h1>VinAI Admissions MAS</h1><p>LangGraph · Agent Harness · local + web search · source-aware validation</p>
<div class='grid'><section><h2>Query</h2><label for='query'>Câu hỏi ứng viên</label><textarea id='query'>Điều kiện tham gia chương trình AI là gì?</textarea><label for='profile'>Candidate profile JSON</label><input id='profile' value='{"education":"student","experience":"basic AI"}'><button id='ask' onclick='ask()'>Tra cứu</button><div id='status' class='muted'></div></section>
<section><h2>Answer</h2><div id='answer'>Chưa có truy vấn.</div><div id='metrics'></div><h3>Sources</h3><div id='sources' class='stack'></div></section></div>
<section><h2>Evidence</h2><div id='evidence' class='stack'>Chưa có evidence.</div></section>
<section><h2>Execution trace</h2><div id='events' class='stack'>Chưa có log.</div></section>
<section><h2>Prompt XML</h2><pre id='xml'></pre></section>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function ask(){const button=document.getElementById('ask');button.disabled=true;document.getElementById('status').textContent='Đang chạy Orchestrator → Searcher → Validator → Synthesis...';try{let profile={};try{profile=JSON.parse(document.getElementById('profile').value)}catch(e){throw Error('Candidate profile phải là JSON hợp lệ')}const response=await fetch('/api/query',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:document.getElementById('query').value,profile,context:{session_id:'web-demo'}})});const data=await response.json();if(!response.ok)throw Error(data.error||'Query failed');document.getElementById('answer').textContent=data.response;const v=data.validation||{};document.getElementById('metrics').innerHTML=`<span class='metric'>validation: <b class='${v.passed?'ok':'warn'}'>${esc(v.passed)}</b></span><span class='metric'>evidence: ${esc(v.evidence_count)}</span><span class='metric'>relevance: ${esc(v.avg_relevance)}</span><span class='metric'>trust: ${esc(v.avg_source_trust)}</span><span class='metric'>risk: ${esc((data.orchestration||{}).risk_level)}</span>`;document.getElementById('sources').innerHTML=(data.sources||[]).map(s=>`<div class='source'><b>${esc(s.title)}</b><br><span class='muted'>${esc(s.source_id)} · trust ${esc(s.trust_score)} · <a href='${esc(s.uri)}' target='_blank' rel='noreferrer'>open source</a></span></div>`).join('')||'<span class=muted>No approved sources.</span>';document.getElementById('evidence').innerHTML=(data.evidence||[]).map(e=>`<div class='evidence'><b>${esc(e.evidence_id)}</b> · ${esc(e.locator)}<br><span class='muted'>source ${esc(e.source_id)} · relevance ${esc(e.relevance_score)} · trust ${esc(e.source_trust_score)}</span><br>${esc(e.quote)}</div>`).join('')||'<span class=muted>No evidence passed validation.</span>';document.getElementById('xml').textContent=data.prompt_xml||'';const logs=await (await fetch('/api/logs')).json();document.getElementById('events').innerHTML=logs.filter(x=>x.request_id===data.request_id).map(x=>`<div class='event'><b>${esc(x.step)}</b> · ${esc(x.component)}<br><span class='muted'>${esc(x.timestamp)}</span></div>`).join('')||'<span class=muted>No trace.</span>';document.getElementById('status').textContent=`Completed ${data.request_id}`}catch(error){document.getElementById('status').textContent=error.message;document.getElementById('answer').textContent='Không thể xử lý request.'}finally{button.disabled=false}}
</script></body></html>"""
